# Generated by Django 3.2.8 on 2021-10-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('Kids (Hasta 7 años)', 'Kids (Hasta 7 años)'), ('Infantil A (8-9 años)', 'Infantil A (8-9 años)'), ('Infantil B (10-11 años)', 'Infantil B (10-11 años)'), ('Cadete (12-13 años)', 'Cadete (12-13 años)'), ('Juvenil A (14-15 años)', 'Juvenil A (14-15 años)'), ('Juvenil B (16-17 años)', 'Juvenil B (16-17 años)'), ('Adultos (18-35 años)', 'Adultos (18-35 años)'), ('Seniors (+35 años)', 'Seniors (+35 años)')], max_length=100, null=True)),
                ('graduacion', models.CharField(blank=True, choices=[('Blanco - Blanco Punta Amarilla', 'Blanco - Blanco Punta Amarilla'), ('Amarillo - Verde Punta Azul', 'Amarillo - Verde Punta Azul'), ('Azul - Rojo Punta Negra', 'Azul - Rojo Punta Negra'), ('I Dan', 'I Dan'), ('II Dan', 'II Dan'), ('III Dan', 'III Dan'), ('IV Dan - VI Dan', 'IV Dan - VI Dan')], max_length=100, null=True)),
                ('academia', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('dni', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
