# Generated by Django 3.2.8 on 2021-10-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competidor',
            options={'verbose_name': 'Competidor', 'verbose_name_plural': 'Competidores'},
        ),
    ]
